config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  has_many :posts, dependent: :destroy      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        flash[:success] = "Your post has been created!"
        redirect_to posts_path
      else
        flash[:alert] = "Your new post couldn't be created!  Please check the form."
        render :new
      end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Your post has been updated!"
      redirect_to(post_path(@post))
    else
      flash[:alert] = "Sorry, we couldn't update your post at this time."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
  end  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Photogram</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'partials/navbar' %>
        
        <div class="container">
            <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
            <% end %>

            <%= yield %>
        </div>
    </body>
</html>

app/views/partials/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="navbar-container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
                <%= link_to "Photogram", root_path %>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li>
                    <%= link_to "New Post", new_post_path %>
                </li>
                <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Login", new_user_session_path %>
                </li>
                <li>
                    <%= link_to "Register", new_user_registration_path %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>

<%= render 'partials/form' %>


<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          <%= post.user.user_name %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'partials/form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
    <div class="post">
        <div class="post-head">
            <div class="name">
                <%= @post.user.user_name %>
            </div>
        </div>
        <div class="image center-block">
            <%= image_tag @post.image.url(:medium) %>
        </div>
        <p class="caption">
            <%= @post.caption %>
        </p>

        <% if @post.user.id == current_user.id %>
          <div class="text-center edit-links">
              <%= link_to "Edit Post", edit_post_path(@post) %>
              |
              <%= link_to "Cancel", posts_path %>
          </div>
        <% else %>
          <div class="text-center edit-links">
              <%= link_to "Cancel", posts_path %>
          </div>
        <% end %>

    </div>
</div>